name: Package and Release png-chunk-msg-cli

on:
  push:
    tags:
      - 'cli-release*'  # 触发条件：当推送以 'cli-release' 开头的标签时触发

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # 定义支持的平台

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test -p png-chunk-msg-cli 
    - name: Build
      run: cargo build --release --package png-chunk-msg-cli
    - name: Print GITHUB_TOKEN permissions
      run: |
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user | jq

    - name: Set file extension for Windows and Zip package
      run: |
          # Set the binary name based on the platform
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            BINARY_NAME="png-chunk-msg-cli.exe"
          else
            BINARY_NAME="png-chunk-msg-cli"
          fi
          echo "Binary name is $BINARY_NAME"

          mkdir -p upload_files
          cp target/release/$BINARY_NAME  upload_files
          # -C 是指不包括目录本身
          tar -czvf upload_files/png-chunk-msg-cli-${{ runner.os }}.tar.gz -C upload_files $BINARY_NAME
        
    - name: Publish zip
      uses: softprops/action-gh-release@v2
      with:
        files: upload_files/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
   
      
      

