name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # 定义支持的平台

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --package png-chunk-msg-cli
    - name: find 
      run: |
       mkdir -p upload_files
       find target/release -type f ! -name '*.d' \( -name 'png-chunk-msg-cli' -or -name 'png-chunk-msg-cli.exe' \) -exec tar -czvf upload_files/png-chunk-msg-cli-${{ runner.os }}.tar.gz {} +
       ls upload_files
